name: Backend Lint

on: 
  pull_request:
    paths:
      - 'backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.5

      - name: Install dependencies and run lint checks
        working-directory: ./backend
        run: |
          go mod download
          gofmt -s -l . | grep -q . && (echo "Run gofmt!" && exit 1) || true
          go vet ./...
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2
          golangci-lint run --timeout=5m ./...
