name: Backend Lint

on: 
  pull_request:
    paths:
      - 'backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.5

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.56.2
          working-directory: ./backend